version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: app
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - "./.data/postgres:/var/lib/postgresql"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
  gate:
    build:
      context: ./gate-simulator
      dockerfile: Dockerfile